ALTER TABLE `utilisateur`
ADD
	`date_crea` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD
	`utilisateur_crea` INT NULL DEFAULT NULL,
ADD
	`date_modif` DATETIME on update CURRENT_TIMESTAMP NULL DEFAULT NULL,
ADD
	`utilisateur_modif` INT NULL DEFAULT NULL;

ALTER TABLE `gerant`
ADD
	`date_crea` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD
	`utilisateur_crea` INT NULL DEFAULT NULL,
ADD
	`date_modif` DATETIME on update CURRENT_TIMESTAMP NULL DEFAULT NULL,
ADD
	`utilisateur_modif` INT NULL DEFAULT NULL;