DROP TABLE IF EXISTS formulaire;
CREATE TABLE IF NOT EXISTS formulaire (
    id_form INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
    date_form VARCHAR(10),
    adresse TEXT,
    importance TEXT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

DROP TABLE IF EXISTS message;
CREATE TABLE IF NOT EXISTS message (
    id_message INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
    contenu TEXT,
    objet TEXT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

DROP TABLE IF EXISTS photo;
CREATE TABLE IF NOT EXISTS photo (
    id_photo INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
    date_photo VARCHAR(10),
    position TEXT,
    taille TEXT,
    source TEXT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

DROP TABLE IF EXISTS `role`;
CREATE TABLE IF NOT EXISTS `role` ( 
    id_role INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
    libelle TEXT NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

DROP TABLE IF EXISTS users;
CREATE TABLE IF NOT EXISTS users (
    id_user INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
    username VARCHAR(50) NOT NULL,
    email VARCHAR(100) NOT NULL,
    password TEXT NOT NULL,
    adresse TEXT NOT NULL,
    tel NUMERIC NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

DROP TABLE IF EXISTS ville;
CREATE TABLE IF NOT EXISTS ville (
    id_ville INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
    code_postal NUMERIC,
    nom TEXT,
    email TEXT,
    tel NUMERIC,
    adresse TEXT,
    departement TEXT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;